os:
- linux
- osx
language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- '6'
branches:
  only:
  - master
addons:
  apt:
    packages:
    - xvfb
before_install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
